name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          # args: -f -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          args: -f -pdf -interaction=nonstopmode
          working_directory: ./paper
